### PR TITLE
fix: avoid exceptions and repeated waits during Nacos client graceful shutdown

### LINKED ISSUE #4064: Nacos module may throw exceptions or wait multiple times during graceful shutdown
**Which Component**
Nacos Discovery

**Describe the bug**
Nacos Client 在停机时，NacosAutoServiceRegistration 通过 `@EventListener` 实现了监听 spring 的 ContextClosedEvent，并在该事件发布时进行停机前同步等待，然而这里存在 2 个隐患：
1. 在 SpringCloud 场景下 NamedContextFactory 的多个 spring 子 context 关闭时，都会发布 ContextClosedEvent 事件，如果此时 NacosAutoServiceRegistration 这个 event lister 尚未销毁，也会触发 Nacos 客户端的优雅停机等待，导致停机耗时大幅加长
2. 由于 NacosAutoServiceRegistration 是通过 `@EventListener` 进行的 Spring 事件监听，在 spring 主容器关闭和销毁 bean 时，可能会先销毁 NacosAutoServiceRegistration 这个 bean，再去会销毁 NamedContextFactory 这个 bean（和问题 1 顺序相反），而后者在销毁时，会触发 NamedContextFactory 创建的子 context 进行 close，这些 context 在 close 时，检索 spring event Listener 时依然会检索出 NacosAutoServiceRegistration（通过查阅 spring 社区 issue，这似乎是一个特性，而非 bug），由于该 bean 已经销毁并且业务主上下文正在关闭，进而会进行 bean 创建，从而抛出 BeanCreationNotAllowedException。

When shutting down, NacosAutoServiceRegistration uses `@EventListener` to listen for Spring’s ContextClosedEvent and performs a synchronous pre-shutdown wait when the event is published. However, there are two risks:
1. In Spring Cloud scenarios, when multiple child contexts created by NamedContextFactory are closed, each publishes a ContextClosedEvent. If the NacosAutoServiceRegistration event listener has not yet been destroyed, it will be invoked for each event, triggering the Nacos client’s graceful-shutdown wait multiple times and significantly prolonging shutdown.
2. Because NacosAutoServiceRegistration listens via `@EventListener`, during shutdown of the primary Spring container it’s possible that the NacosAutoServiceRegistration bean is destroyed before the NamedContextFactory bean (It is in the opposite order as described in Question 1). When NamedContextFactory is destroyed, it closes the child contexts it created. While those contexts are closing, Spring’s event-listener lookup may still return NacosAutoServiceRegistration (per Spring community issues, this appears to be by design rather than a bug). Since that bean has already been destroyed and the main application context is closing, Spring attempts to create the bean again, resulting in a BeanCreationNotAllowedException.

**To Reproduce**
想要复现问题，你可以在项目中引入 feign 客户端配置，然后进行如下操作：
复现问题 1，你在创建任何业务 bean 的时候不要依赖 feign 客户端，可以在最终 spring 容器启动完毕后对 feign 客户端进行 getBean，然后发起调用。关闭应用时就可以复现问题。
复现问题 2，你可以直接通过 @Autowired （其他方式也行，只要是依赖注入就可以）将 feign 客户端注入到某个 service 中，然后正常进行调用。关闭应用时就可以复现问题。

Prerequisite: Add Feign client configuration to the project.
Reproduce Issue 1:
Do not depend on the Feign client when creating your business beans.
After the Spring application context has fully started, obtain the Feign client via ApplicationContext.getBean(...) and make a call.
Shut down the application to observe the issue.
Reproduce Issue 2:
Inject the Feign client into a service using @Autowired (or any injection method you prefer, e.g., constructor injection) and invoke it normally.
Shut down the application to observe the issue.

相似的问题还有：
https://github.com/alibaba/spring-cloud-alibaba/issues/4057
https://github.com/alibaba/spring-cloud-alibaba/issues/4054

### PR DESCRIPTION
**Pull request by uuuyuqi**
### Describe what this PR does / why we need it
refer to https://github.com/alibaba/spring-cloud-alibaba/issues/4064

### Does this pull request fix one issue?
Fixes #4064

### Describe how you did it
Refactored the Nacos client’s graceful-shutdown logic by extracting a dedicated event listener to handle it.

### Describe how to verify it
Added unit tests and performed local verification.

### CODE REVIEW

File: spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosGracefulShutdownDelegate.java [hunk 1]
```diff
@@ -0,0 +1,85 @@
+/*
+ * Copyright 2013-2023 the original author or authors.
```
Comment (yuluo-yx) [inline spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosGracefulShutdownDelegate.java]: `2013-2025`

File: spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosGracefulShutdownDelegate.java [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+
+		doGracefulShutdown();
+	}
+
+	protected void doGracefulShutdown() {
+		try {
+			autoServiceRegistration.stop();
+			Integer gracefulShutdownWaitTime = this.nacosDiscoveryProperties.getGracefulShutdownWaitTime();
+			if (gracefulShutdownWaitTime != null && gracefulShutdownWaitTime > 0) {
+				ThreadUtils.sleep(gracefulShutdownWaitTime);
```
Comment (yuluo-yx) [inline spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosGracefulShutdownDelegate.java:72]: add more log, when user not config nacos shutdown time, use defaule value.

Comment (uuuyuqi) [reply spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosGracefulShutdownDelegate.java:72]: ok

**Review by yuluo-yx — APPROVED** [review]
LGTM
