### PR TITLE
Fix nacos discovery/config log 

### LINKED ISSUE #3133: Nacos-Client log print to application logs, not print to nacos' log
**Which Component**
Nacos Discovery/Config

**Describe the bug**
Relative issue #1931.

After the issue fix problem, the problem fixed by some old version.

But in some new version, the problem started again. After my debug and research. I fount that the problem is caused by the spring will call the `LoggingSystem.initialize` from `PropertySourceBootstrapConfiguration` after all `ApplicationEnvironmentPreparedEvent`.

But `NacosLoggingListener` in Nacos Discovery/Config only handle `ApplicationEnvironmentPreparedEvent` not loadConfiguration again after `PropertySourceBootstrapConfiguration`. So the log config still be overwrite by spring.

**To Reproduce**
1. Go to 'nacos-discovery-spring-cloud-config-client-example' in tag `2.2.9.RELEASE`
2. Run on 'SpringCloudConfigClientApplication'
3. See nacos client log print into console.

**Expected behavior**
nacos client log print into ${user.home}/naming.log or config.log 

**Screenshots**

**Additional context**
MacOS  、Java8 、 Version 2.2.6.RELEASE ~ 2.2.9.RELEASE

I don't test for 2021.X and 2022.X. Please community to check and fix.

### PR DESCRIPTION
**Pull request by ruansheng8**
### Describe what this PR does / why we need it
Fixed #3133

### CODE REVIEW

File: spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/logging/NacosLoggingListener.java [hunk 1]
```diff
@@ -30,6 +30,7 @@
  *
  * @author mai.jh
  */
+@Deprecated
```
Comment (steverao) [inline spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/logging/NacosLoggingListener.java:33]: Whether we delete the invalid listener directly?

File: spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/logging/NacosLoggingListener.java [hunk 2]
```diff
@@ -30,6 +30,7 @@
  *
  * @author mai.jh
  */
+@Deprecated
```
Comment (steverao) [inline spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/logging/NacosLoggingListener.java:33]: Same problem like above.

File: spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/logging/NacosLoggingAppRunListener.java [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+ */
+public class NacosLoggingAppRunListener implements SpringApplicationRunListener, Ordered {
+
+	public NacosLoggingAppRunListener(SpringApplication application, String[] args) {
+
+	}
+
+	@Override
+	public void environmentPrepared(ConfigurableEnvironment environment) {
+		NacosLogging.getInstance().loadConfiguration();
```
Comment (steverao) [inline spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/logging/NacosLoggingAppRunListener.java:40]: Whether we don't need do load configuration here? because I see it doesn't have clearing logContext logic before here and just have it before contextPrepared like following:
image

Comment (ruansheng8) [reply spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/logging/NacosLoggingAppRunListener.java:40]: The Nacos client will create connection after `environmentPrepared`, and log messages will be output to the console. If the `NacosLogging.getInstance().loadConfiguration()` is reset after `contextPrepared`, some of the log messages will be output to the console between `environmentPrepared` and `contextPrepared`.

File: spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/logging/NacosLoggingListener.java (hunk 1 above)
Comment (ruansheng8) [reply spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/logging/NacosLoggingListener.java:33]: The reason why these two classes were not directly deleted is that there may be users who depend on these classes for some customization operations (although this possibility is small), so they are marked as `deprecated` first and will be removed in the next version.

**Review by steverao — APPROVED** [review]
LGTM, thanks @ruansheng8

**Comment by ruansheng8** [comment]
`TODO:` I will remove `NacosLoggingListener` in the next version.
