### PR TITLE
fix: incorrect cross-cluster call warning when clusterName is not set

### LINKED ISSUE #4020: The log was incorrectly printed: "A cross-cluster call occurs"
**Which Component**
NacosLoadBalancer

**Describe the bug**
```
String clusterName = this.nacosDiscoveryProperties.getClusterName();
List<ServiceInstance> instancesToChoose = serviceInstances;
if (StringUtils.isNotBlank(clusterName)) {
    List<ServiceInstance> sameClusterInstances = serviceInstances.stream()
                             .filter(serviceInstance -> {
				     String cluster = serviceInstance.getMetadata().get("nacos.cluster");
				     return StringUtils.equals(cluster, clusterName);
				 }).collect(Collectors.toList());
    if (!CollectionUtils.isEmpty(sameClusterInstances)) {
        instancesToChoose = sameClusterInstances;
    }
} else {
    log.warn("A cross-cluster call occurs，name = {}, clusterName = {}, instance = {}",
						serviceId, clusterName, serviceInstances);
}
```
Due to this pull request（https://github.com/alibaba/spring-cloud-alibaba/pull/3771）, the default value for com.alibaba.cloud.nacos.NacosDiscoveryProperties#clusterName was removed. When the user does not explicitly specify a clusterName, the method com.alibaba.cloud.nacos.loadbalancer.NacosLoadBalancer#getInstanceResponse will directly enter the else block, causing the message "A cross-cluster call occurs" to be logged incorrectly.
应修改为：
```
String clusterName = this.nacosDiscoveryProperties.getClusterName();
List<ServiceInstance> instancesToChoose = serviceInstances;
if (StringUtils.isNotBlank(clusterName)) {
    List<ServiceInstance> sameClusterInstances = serviceInstances.stream()
                             .filter(serviceInstance -> {
				     String cluster = serviceInstance.getMetadata().get("nacos.cluster");
				     return StringUtils.equals(cluster, clusterName);
				 }).collect(Collectors.toList());
    if (!CollectionUtils.isEmpty(sameClusterInstances)) {
        instancesToChoose = sameClusterInstances;
    } else {
    log.warn("A cross-cluster call occurs，name = {}, clusterName = {}, instance = {}",
						serviceId, clusterName, serviceInstances);
    }
} 
```
			

**Additional context**
spring-cloud-alibaba-dependencies 2021.0.6.2

### PR DESCRIPTION
**Pull request by daguimu**
### Describe what this PR does / why we need it

In `NacosLoadBalancer.getInstanceResponse()`, the "A cross-cluster call occurs" warning log is incorrectly placed in the outer `else` block, which triggers when `clusterName` is blank (null or empty). Since PR #3771 removed the default value for `clusterName`, this warning fires on every load balancing request when users don't explicitly configure a cluster name.

The warning should only appear when `clusterName` IS configured but no same-cluster instances are found — that is the actual cross-cluster call scenario.

### Does this pull request fix one issue?

Fixes #4020

### Describe how you did it

Moved the `else` block with the warning log from the outer `if (StringUtils.isNotBlank(clusterName))` into the inner `if (!CollectionUtils.isEmpty(sameClusterInstances))`.

Before (incorrect):
```java
if (StringUtils.isNotBlank(clusterName)) {
    // filter same cluster instances
    if (!CollectionUtils.isEmpty(sameClusterInstances)) {
        instancesToChoose = sameClusterInstances;
    }
}
else {
    log.warn("A cross-cluster call occurs..."); // triggers when clusterName is BLANK
}
```

After (correct):
```java
if (StringUtils.isNotBlank(clusterName)) {
    // filter same cluster instances
    if (!CollectionUtils.isEmpty(sameClusterInstances)) {
        instancesToChoose = sameClusterInstances;
    }
    else {
        log.warn("A cross-cluster call occurs..."); // triggers when clusterName is SET but no match
    }
}
```

### Describe how to verify it

1. Start a Spring Cloud Alibaba application with Nacos discovery without setting `spring.cloud.nacos.discovery.cluster-name`
2. Make load-balanced requests
3. Verify no "A cross-cluster call occurs" warning in logs

### Tests Added

| Change Point | Test |
|-------------|------|
| Blank clusterName should not warn | `blankClusterNameShouldNotWarnCrossCluster()` |
| Empty clusterName should not warn | `emptyClusterNameShouldNotWarnCrossCluster()` |
| Same cluster instances selected correctly | `sameClusterShouldSelectSameClusterInstance()` |
| No same-cluster instances still returns response | `noSameClusterInstancesShouldStillReturnResponse()` |
| Empty instances returns EmptyResponse | `emptyServiceInstancesShouldReturnEmptyResponse()` |

### Special notes for reviews

PR #4021 proposed the same fix for the `2021.x` branch. This PR applies it to the current `2025.1.x` branch with comprehensive unit tests.

### CODE REVIEW

**Comment by uuuyuqi** [comment]
Thanks for the fix. One follow-up concern: this warning is still emitted from the request path in `NacosLoadBalancer#getInstanceResponse()`. That means if a service stays in a real cross-cluster fallback state for some time, the log can still be printed once per request and flood the logs under traffic.

Would you consider adding some form of throttling here, for example:
- log at most once per time window per `(serviceId, clusterName)`, or
- log only on state transition (entering cross-cluster fallback), and suppress repeats until recovery

The current fix removes the false positives, which is great, but rate-limiting the warning would make the behavior much safer in sustained fallback scenarios.

**Comment by daguimu** [comment]
@uuuyuqi Good point! I've updated this PR to include log throttling — the cross-cluster warning now logs at most once per 5 minutes per `(serviceId, clusterName)` using a `ConcurrentHashMap<String, Long>` timestamp tracker. This prevents log flooding under sustained cross-cluster fallback traffic while still surfacing the warning when it first occurs.

Added test: `crossClusterWarnShouldBeThrottled()` — verifies the throttle state is tracked correctly after repeated cross-cluster calls.

File: spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/loadbalancer/NacosLoadBalancer.java [hunk 1]
```diff
@@ -183,4 +187,17 @@ private Response<ServiceInstance> getInstanceResponse(Request<?> request,
 		}
 	}
 
+	private void warnCrossClusterThrottled(String clusterName, List<ServiceInstance> serviceInstances) {
```
Comment (uuuyuqi) [inline spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/loadbalancer/NacosLoadBalancer.java:188]: Map would also need a maximum keysize limit, but I do not think it needs to be that complex.

We probably do not need to distinguish by `clusterName` or keep a `ConcurrentHashMap` for this warning. A much simpler approach should be enough for this PR: keep a single `lastWarnLogTime` on `NacosLoadBalancer` and only log once every 10 seconds, e.g. `currentMillis - lastWarnLogTime > 10s`.

I do not think we need locking for this field either. This is only best-effort log throttling, so occasional duplicate logs under concurrency are acceptable from an engineering perspective. If we want a minimal concurrency safeguard while keeping it simple, `volatile long lastWarnLogTime` would be sufficient.

**Review by uuuyuqi — CHANGES_REQUESTED** [review]

File: spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/loadbalancer/NacosLoadBalancer.java (hunk 1 above)
Comment (daguimu) [reply spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/loadbalancer/NacosLoadBalancer.java:188]: Fixed. Replaced `ConcurrentHashMap` with a single `volatile long lastWarnLogTime`, throttle interval set to 10 seconds, no locking. Updated tests accordingly.

**Review by uuuyuqi — APPROVED** [review]
LGTM
